"""add special_request to booking

Revision ID: 5608754280aa
Revises: cc60ee5a8fd9
Create Date: 2026-07-23 11:18:12.218254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5608754280aa'
down_revision = 'cc60ee5a8fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_request', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('special_request')

    # ### end Alembic commands ###
