"""add requested_by to event

Revision ID: cc60ee5a8fd9
Revises: 45b9181f8155
Create Date: 2026-07-21 12:44:11.537883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc60ee5a8fd9'
down_revision = '45b9181f8155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_event_requested_by_user', 'user', ['requested_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('requested_by')

    # ### end Alembic commands ###
